### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by jooewood** [jiangfeng1124/ChemRxnExtractor#10]
Run
```
from chemrxnextractor import RxnExtractor

model_dir="models" # directory saving both prod and role models
rxn_extractor = RxnExtractor(model_dir)

test_file = './tests/data/raw.txt'
with open(test_file, "r") as f:
    sents = f.read().splitlines()
rxns = rxn_extractor.get_reactions(sents)
```
Error
```
Loading product extractor from cre_models_v0.1/prod...done
Loading role extractor from cre_models_v0.1/role...done
Traceback (most recent call last):

  File "/tmp/ipykernel_892180/2406664485.py", line 12, in <module>
    rxns = rxn_extractor.get_reactions(sents)

  File "/home/zdx/src/ChemRxnExtractor/chemrxnextractor/cre.py", line 230, in get_reactions
    token_type_ids=batch['token_type_ids']

  File "/home/zdx/anaconda3/envs/chemrxnextractor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/zdx/src/ChemRxnExtractor/chemrxnextractor/models/model.py", line 319, in forward
    extended_cls_h = outputs[1].unsqueeze(1).expand(batch_size, seq_length, hidden_dim)

  File "/home/zdx/anaconda3/envs/chemrxnextractor/lib/python3.7/site-packages/transformers/utils/generic.py", line 222, in __getitem__
    return self.to_tuple()[k]

IndexError: tuple index out of range
```
I don't know how to solve it, any suggestions? Thanks!

**Comment by TheOnlylight** [comment]
how do you solve it? I encountered exactly the same problem

**Comment by damianmartix** [comment]
@jooewood  or @TheOnlylight  Have you found the solution?

**Comment by tom832** [comment]
> @jooewood or @TheOnlylight Have you found the solution?

I have also met this issue, and I found it was caused by the unsuitable version of transformers package.

**Comment by damianmartix** [comment]
@tom832 Thanks, it works now using the transformers package v3.0.2
